version: '3.8'

services:
  web:
    build: .
    container_name: dept_web
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False


