# Generated by Django 6.0.5 on 2026-06-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admission_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(default='자유전공학부', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='signup_step',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
