# Generated by Django 6.0.5 on 2026-06-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessiblePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url_name', models.CharField(help_text='Django URL pattern name or external/absolute path', max_length=100)),
                ('allowed_school', models.CharField(default='All', max_length=100)),
                ('allowed_department', models.CharField(default='All', max_length=100)),
                ('icon', models.CharField(default='ri-links-line', max_length=50)),
                ('category', models.CharField(default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
