# Generated by Django 6.0.5 on 2026-06-20 08:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('friend', '친구찾기'), ('study', '스터디'), ('project', '프로젝트')], max_length=20)),
                ('size_category', models.CharField(choices=[('small', '적음'), ('medium', '중간'), ('large', '많음')], max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('tags', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('forming', 'forming'), ('min_reached_grace', 'min_reached_grace'), ('confirmed', 'confirmed'), ('closed_timeout', 'closed_timeout')], default='forming', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('min_reached_at', models.DateTimeField(blank=True, null=True)),
                ('last_member_change_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('friend', '친구찾기'), ('study', '스터디'), ('project', '프로젝트')], max_length=20)),
                ('detail_text', models.TextField()),
                ('size_category', models.CharField(choices=[('small', '적음'), ('medium', '중간'), ('large', '많음')], max_length=20)),
                ('status', models.CharField(choices=[('pending_matching', '매칭 중'), ('matched_waiting', '선택지 대기'), ('registered', '매칭 대기 등록'), ('matched', '매칭 성사 완료'), ('expired', '만료')], default='pending_matching', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='needs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group', 'user')},
            },
        ),
    ]
