# Generated by Django 6.0.5 on 2026-06-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_group_need_groupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='recommended_groups',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
