# Generated by Django 5.2.15 on 2026-06-20 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_groupmember_group_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessiblePage',
        ),
    ]
